site_name: TKSL Mind and Mental Factors
theme: 
  name: material
plugins:
  - mkdocs-video
nav:
  - "1 Mind and Mental Factors": topics/01_Mind.md
  - "2 Omnipresent MFs": topics/02_OmnipresentMFs.md
  - "3 Object Ascertaining MFs": topics/03_ObjectAscertainingMFs.md
  - "Definitions": definitions.md